# Generated by Django 5.0 on 2023-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='pagenizer_size',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
