# Generated by Django 5.0 on 2023-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0002_userpreferences_pagenizer_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='pagenizer_size',
            new_name='paginate_by',
        ),
    ]
