# Generated by Django 5.0 on 2023-12-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0003_rename_pagenizer_size_userpreferences_paginate_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movierss',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='scan_from_page',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
