# Generated by Django 5.0 on 2023-12-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0004_alter_movierss_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='paginate_by',
        ),
    ]
