# Generated by Django 5.0 on 2023-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0005_remove_userpreferences_paginate_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierss',
            name='kinorium_id',
        ),
        migrations.RemoveField(
            model_name='movierss',
            name='kinorium_partial_match',
        ),
        migrations.AddField(
            model_name='movierss',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Низкий приоритет'), (1, 'Обычный приоритет'), (2, 'Отложено')], default=0, verbose_name='Priority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='scan_from_page',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если длительный скан оборвался, можно его продолжить с этой страницы до последней.', null=True),
        ),
    ]
