# Generated by Django 5.0 on 2023-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0006_remove_movierss_kinorium_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='poster',
            field=models.CharField(max_length=100),
        ),
    ]
