# Generated by Django 5.0 on 2023-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0007_alter_movierss_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierss',
            name='kinorium_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movierss',
            name='kinorium_partial_match',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='ignored',
            field=models.BooleanField(default=False, help_text='Пользователь не хочет, чтобы этот фильм снова появился в ленте'),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (0, 'Обычный'), (2, 'Отложено'), (3, 'Отложено')], verbose_name='Priority'),
        ),
    ]
