# Generated by Django 5.0 on 2023-12-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0009_rename_ignored_movierss_ignored_deprecated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierss',
            old_name='low_priority',
            new_name='low_priority_deprecated',
        ),
    ]
