# Generated by Django 5.0 on 2023-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0010_rename_low_priority_movierss_low_priority_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='kinorium_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='На данный момент не используется, потому что мы не можем получить ID из Кинориума', null=True),
        ),
    ]
