# Generated by Django 5.0.2 on 2024-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0011_alter_movierss_kinorium_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierss',
            name='dubbing',
            field=models.BooleanField(default=False, help_text='Раздача имеет дубляж или ПМ'),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='plot',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (0, 'Обычный'), (2, 'Отложено'), (3, 'Отказ'), (4, 'Жду дубляж'), (5, 'Найден дубляж или ПМ')], verbose_name='Priority'),
        ),
    ]
