# Generated by Django 5.0.2 on 2024-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0012_movierss_dubbing_alter_movierss_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='dubbing',
            field=models.BooleanField(blank=True, help_text='Раздача имеет дубляж или ПМ', null=True),
        ),
    ]
