# Generated by Django 5.0.2 on 2024-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0013_alter_movierss_dubbing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierss',
            name='dubbing',
        ),
        migrations.AddField(
            model_name='movierss',
            name='dubbed',
            field=models.BooleanField(blank=True, help_text='Раздача имеет дубляж или ПМ. Нужно для передачи этой информации из сканера в чекер.', null=True),
        ),
    ]
