# Generated by Django 5.0.2 on 2024-05-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0014_remove_movierss_dubbing_movierss_dubbed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
