# Generated by Django 5.0.2 on 2024-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0015_alter_movierss_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='plex_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
