# Generated by Django 5.0.2 on 2024-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0017_userpreferences_plex_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='ignore_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
