# Generated by Django 5.0.2 on 2024-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0018_userpreferences_ignore_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='plot',
            field=models.CharField(max_length=1000),
        ),
    ]
