# Generated by Django 5.1.5 on 2025-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0019_alter_movierss_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='cookie_pass',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='cookie_uid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='torrents_hotfolder',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
