# Generated by Django 5.1.5 on 2025-09-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0020_userpreferences_cookie_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='kinozal_domen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
