# Generated by Django 5.1.5 on 2025-09-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0021_userpreferences_kinozal_domen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='kinozal_domen',
            new_name='kinozal_domain',
        ),
    ]
