# Generated by Django 5.1.5 on 2025-09-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0022_rename_kinozal_domen_userpreferences_kinozal_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preferences', 'verbose_name_plural': 'User Preferences'},
        ),
    ]
