# Generated by Django 5.1.5 on 2025-12-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0023_alter_userpreferences_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tmdb_api_key',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='tmdb_v4_read_access_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
