# Generated by Django 5.1.5 on 2025-12-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0024_userpreferences_tmdb_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='tmdb_api_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tmdb_v4_read_access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
