# Generated by Django 5.1.5 on 2025-12-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0025_alter_userpreferences_tmdb_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='tmdb_api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
