# Generated by Django 5.1.5 on 2025-12-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0026_alter_userpreferences_tmdb_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tmdb_v4_authenticated_access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
