# Generated by Django 5.1.5 on 2025-12-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefilter', '0027_userpreferences_tmdb_v4_authenticated_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='tmdb_v4_authenticated_access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tmdb_v4_read_access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
