# Generated by Django 6.0 on 2025-12-29 06:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=2, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('photo', models.CharField(blank=True, help_text='Относительный путь к фото (например: /pynwU6PGLAdDE840rC9m6jEahWg.jpg)', max_length=255, null=True, verbose_name='Путь к фото')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('movie_type', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('cartoon', 'Мультфильм'), ('anime', 'Аниме'), ('show', 'Шоу')], default='movie', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('announced', 'Анонсирован'), ('production', 'В производстве'), ('post_production', 'Пост-продакшн'), ('released', 'Вышел'), ('cancelled', 'Отменен')], default='released', max_length=20, verbose_name='Статус')),
                ('poster', models.CharField(blank=True, help_text='Относительный путь к фото (например: /pynwU6PGLAdDE840rC9m6jEahWg.jpg)', max_length=255, null=True, verbose_name='Путь к фото')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Ссылка на трейлер')),
                ('age_rating', models.CharField(blank=True, max_length=10, verbose_name='Возрастной рейтинг')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бюджет')),
                ('box_office', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сборы')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг IMDb')),
                ('imdb_votes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Голосов IMDb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('countries', models.ManyToManyField(related_name='movies', to='vault.country', verbose_name='Страны')),
                ('genres', models.ManyToManyField(related_name='movies', to='vault.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vault.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vault.movie')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Актер'), ('director', 'Режиссер'), ('producer', 'Продюсер'), ('writer', 'Сценарист'), ('composer', 'Композитор'), ('operator', 'Оператор'), ('editor', 'Монтажер')], max_length=20, verbose_name='Роль')),
                ('character_name', models.CharField(blank=True, max_length=255, verbose_name='Имя персонажа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_persons', to='vault.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_movies', to='vault.person')),
            ],
            options={
                'verbose_name': 'Участие в фильме',
                'verbose_name_plural': 'Участия в фильмах',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vault.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('review_type', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный'), ('neutral', 'Нейтральный')], max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vault.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('list_type', models.CharField(choices=[('watched', 'Просмотрено'), ('will_watch', 'Буду смотреть'), ('wont_watch', 'Не буду смотреть'), ('favorites', 'Избранное'), ('custom', 'Пользовательский')], max_length=20, verbose_name='Тип списка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный список')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список фильмов',
                'verbose_name_plural': 'Списки фильмов',
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserListMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_lists', to='vault.movie')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_movies', to='vault.userlist')),
            ],
            options={
                'verbose_name': 'Фильм в списке',
                'verbose_name_plural': 'Фильмы в списках',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-year', 'title'], name='vault_movie_year_addaad_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status'], name='vault_movie_status_2a297e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='movieperson',
            unique_together={('movie', 'person', 'role', 'character_name')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
        migrations.AddIndex(
            model_name='userlist',
            index=models.Index(fields=['user', 'is_system'], name='vault_userl_user_id_02da98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together={('user', 'list_type')},
        ),
        migrations.AlterUniqueTogether(
            name='userlistmovie',
            unique_together={('user_list', 'movie')},
        ),
    ]
