# Generated by Django 6.0 on 2025-12-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
    ]
