# Generated by Django 6.0 on 2025-12-30 07:36
# EDITED BY SWASHER

from django.db import migrations


def create_lists_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserList = apps.get_model('vault', 'UserList')

    system_lists = [
        {'list_type': 'watched', 'name': 'Просмотрено', 'order': 1},
        {'list_type': 'will_watch', 'name': 'Буду смотреть', 'order': 2},
        {'list_type': 'wont_watch', 'name': 'Не буду смотреть', 'order': 3},
        {'list_type': 'favorites', 'name': 'Избранное', 'order': 4},
    ]

    for user in User.objects.all():
        for list_data in system_lists:
            # Используем get_or_create для защиты от дублей
            UserList.objects.get_or_create(
                user=user,
                list_type=list_data['list_type'],
                defaults={
                    'name': list_data['name'],
                    'is_system': True,
                    'order': list_data['order'],
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20251230_0930'),
    ]

    operations = [
        migrations.RunPython(create_lists_for_existing_users),
    ]
