# Generated by Django 6.0 on 2025-12-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20251230_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название'),
        ),
    ]
