# Generated by Django 6.0 on 2025-12-30 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_movie_original_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistmovie',
            name='note',
        ),
        migrations.CreateModel(
            name='FavoritePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vault.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная персона',
                'verbose_name_plural': 'Избранные персоны',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'person')},
            },
        ),
        migrations.CreateModel(
            name='MovieNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='vault.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Личная заметка',
                'verbose_name_plural': 'Личные заметки',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
