# Generated by Django 6.0 on 2025-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('vault', '0005_remove_userlistmovie_note_favoriteperson_movienote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(related_name='movies', to='core.country', verbose_name='Страны'),
        ),
    ]
