# Generated by Django 4.2.7 on 2023-11-28 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinoriummovie',
            name='kinozal_original_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kinoriummovie',
            name='kinozal_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kinoriummovie',
            name='kinozal_year',
            field=models.PositiveSmallIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kinoriummovie',
            name='original_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 10, 3, 46, 79767)),
        ),
    ]
