# Generated by Django 4.2.7 on 2023-11-28 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0002_kinoriummovie_kinozal_original_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinoriummovie',
            name='kinozal_original_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='kinoriummovie',
            name='kinozal_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='kinoriummovie',
            name='kinozal_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 10, 18, 44, 559508)),
        ),
    ]
