# Generated by Django 4.2.7 on 2023-11-28 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0003_alter_kinoriummovie_kinozal_original_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 19, 50, 41, 132528)),
        ),
    ]
