# Generated by Django 4.2.7 on 2023-11-29 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0004_alter_userpreferences_last_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='countries',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='genres',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='max_year',
            field=models.PositiveSmallIntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='min_rating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 15, 0, 40, 421107)),
        ),
    ]
