# Generated by Django 4.2.7 on 2023-11-29 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0006_alter_userpreferences_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinozal_id', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=70)),
                ('original_title', models.CharField(max_length=70)),
                ('year', models.PositiveSmallIntegerField()),
                ('date_added', models.DateField()),
                ('imdb_id', models.CharField(max_length=9)),
                ('imdb_rating', models.FloatField()),
                ('kinopoisk_id', models.PositiveSmallIntegerField()),
                ('kinopoisk_rating', models.FloatField()),
                ('genres', models.CharField(max_length=300)),
                ('countries', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('actors', models.CharField(max_length=300)),
                ('plot', models.CharField(max_length=300)),
                ('translate', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=300)),
                ('kinorium_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 20, 8, 43, 787031)),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
