# Generated by Django 4.2.7 on 2023-11-29 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0007_movierss_alter_userpreferences_last_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='kinopoisk_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movierss',
            name='kinorium_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 20, 32, 26, 682190)),
        ),
    ]
