# Generated by Django 4.2.7 on 2023-11-29 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0008_alter_movierss_imdb_id_alter_movierss_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='translate',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 21, 26, 58, 349904)),
        ),
    ]
