# Generated by Django 4.2.7 on 2023-11-30 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0010_alter_movierss_translate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 8, 30, 58, 691062)),
        ),
    ]
