# Generated by Django 4.2.7 on 2023-11-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0012_alter_userpreferences_last_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='last_scan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
