# Generated by Django 4.2.7 on 2023-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0013_alter_userpreferences_last_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierss',
            name='year',
            field=models.CharField(help_text='Год может быть представлен как диапазон: 1982-1994', max_length=9),
        ),
    ]
