# Generated by Django 4.2.7 on 2023-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0014_alter_movierss_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinoriummovie',
            name='kinozal_original_title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
