# Generated by Django 4.2.7 on 2023-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0016_alter_kinoriummovie_kinozal_original_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinoriummovie',
            name='kinozal_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
