# Generated by Django 4.2.7 on 2023-12-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0017_alter_kinoriummovie_kinozal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierss',
            name='low_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='low_countries',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='low_genres',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='low_max_year',
            field=models.PositiveSmallIntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='low_min_rating',
            field=models.FloatField(default=1.0),
        ),
    ]
