# Generated by Django 4.2.7 on 2023-12-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0018_movierss_low_priority_userpreferences_low_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierss',
            name='kinorium_partial_match',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
