# Generated by Django 5.0 on 2023-12-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0020_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinoriummovie',
            name='kinozal_original_title',
        ),
        migrations.RemoveField(
            model_name='kinoriummovie',
            name='kinozal_title',
        ),
        migrations.RemoveField(
            model_name='kinoriummovie',
            name='kinozal_year',
        ),
        migrations.AddField(
            model_name='movierss',
            name='ignored',
            field=models.BooleanField(default=False, help_text='Пользователь не хочет видеть этот фильм.'),
        ),
    ]
